### ISSUE TITLE
Admob Interstitial/Rewarded Ads are not working

### ISSUE THREAD

**Issue by lekeCoder** [deadcoder0904/expo-google-admob#1]
Hello, 

Thanks for the wonderful library and nice example you gave. Please AdmobInterstitial is not showing unlike BannerAds. What can l do? Must l click on a button before it can work? Why can it display on screen transition?

Hope to hear from  soon. Thanks

**Comment by deadcoder0904** [comment]
It works for every case that's why I made this repo.

But when I was making there were problems with Interstitial or Rewarded Ad, I don't remember which.

And yes you have to click the `Blue button` to make Interstitial Ad work. I have made this package 6 months ago so not sure if anything has changed. 

Can you update the packages using [expo-updater](https://github.com/deadcoder0904/expo-updater) & check if it works❓

If it doesn't I'll check it again. Plz confirm❓

**Comment by deadcoder0904** [comment]
Also, check [Expo Forum](https://forums.expo.io/t/google-admob-interstitial-rewarded-video-makes-app-crash/3349/5) for workaround

**Comment by rkbansal** [comment]
It's not working, I think there some wrong with showAd function.

**Comment by deadcoder0904** [comment]
I just checked & updated to SDK v26. I think its a issue with Expo Admob which in turn uses https://github.com/sbugert/react-native-admob I guess so I think it should be put over there or in Expo.

I think the error is - `std: C++ exception` or something like that ;)

**Comment by deadcoder0904** [comment]
I've opened up an issue over at https://github.com/expo/expo/issues/1664 so please check it there. I'll keep it open in the meantime :)

**Comment by deadcoder0904** [comment]
@lekeCoder @rkbansal Its working on Snack. Check https://snack.expo.io/@thetc/admob-example

**Comment by lekeCoder** [comment]
@deadcoder0904 thanks. its working now

**Comment by victoriomolina** [comment]
In my case, I get an error on iOS physical devices (development mode): “Add cannot be presented” (when trying to open an interstitial for a second time).

It perfectly opens multiple times on my emulator, and for a first time on physicals.

I described the problem here: https://github.com/expo/expo/issues/17536
